# Cool T-Shirts Page Visits Funnel

In [21]:
import pandas as pd

visits = pd.read_csv('visits.csv',
                     parse_dates=[1])
cart = pd.read_csv('cart.csv',
                   parse_dates=[1])
checkout = pd.read_csv('checkout.csv',
                       parse_dates=[1])
purchase = pd.read_csv('purchase.csv',
                       parse_dates=[1])
visits.head(10)

                                user_id          visit_time
0  943647ef-3682-4750-a2e1-918ba6f16188 2017-04-07 15:14:00
1  0c3a3dd0-fb64-4eac-bf84-ba069ce409f2 2017-01-26 14:24:00
2  6e0b2d60-4027-4d9a-babd-0e7d40859fb1 2017-08-20 08:23:00
3  6879527e-c5a6-4d14-b2da-50b85212b0ab 2017-11-04 18:15:00
4  a84327ff-5daa-4ba1-b789-d5b4caf81e96 2017-02-27 11:25:00
5  7bc62113-d51d-4e6b-85e0-1cf29e3de74a 2017-06-03 20:05:00
6  6f22cd44-bc63-4449-a9af-2651859da2f9 2017-03-18 23:09:00
7  49a6399b-c095-4e42-92eb-af90abe2bb6a 2017-01-10 12:09:00
8  653c095d-fd74-40dd-ae3b-5a69a2613629 2017-06-27 19:21:00
9  3d9fdac1-aae3-4a01-b448-934d12047468 2017-09-24 06:43:00

In [11]:
cart.head(10)

                                user_id           cart_time
0  2be90e7c-9cca-44e0-bcc5-124b945ff168 2017-11-07 20:45:00
1  4397f73f-1da3-4ab3-91af-762792e25973 2017-05-27 01:35:00
2  a9db3d4b-0a0a-4398-a55a-ebb2c7adf663 2017-03-04 10:38:00
3  b594862a-36c5-47d5-b818-6e9512b939b3 2017-09-27 08:22:00
4  a68a16e2-94f0-4ce8-8ce3-784af0bbb974 2017-07-26 15:48:00
5  0c998868-9961-490b-8ec2-9981ba667027 2017-11-27 08:54:00
6  f783c680-1d9a-437d-9f45-7827299b78fa 2017-06-25 08:08:00
7  f3dd7631-3cf6-4d49-9c6e-b48eda4432b5 2017-01-04 09:57:00
8  4cdd357a-199e-4d81-ae9e-7252fa34ee0f 2017-05-23 22:25:00
9  3c3460b3-a56d-4d92-908d-29dcca34db18 2017-01-06 14:56:00

In [13]:
checkout.head(10)

                                user_id       checkout_time
0  d33bdc47-4afa-45bc-b4e4-dbe948e34c0d 2017-06-25 09:29:00
1  4ac186f0-9954-4fea-8a27-c081e428e34e 2017-04-07 20:11:00
2  3c9c78a7-124a-4b77-8d2e-e1926e011e7d 2017-07-13 11:38:00
3  89fe330a-8966-4756-8f7c-3bdbcd47279a 2017-04-20 16:15:00
4  3ccdaf69-2d30-40de-b083-51372881aedd 2017-01-08 20:52:00
5  a25aad6a-55af-4ddc-92d1-e8c58f855329 2017-01-05 20:07:00
6  3327f8fb-c5a0-421e-a0d1-fb619b79ab45 2017-08-17 04:20:00
7  9c3ea739-7968-429c-87f6-f213ef7b9fcb 2017-04-16 21:22:00
8  cb3ad392-baeb-4e28-a673-eaaf4bac68a4 2017-04-10 21:09:00
9  fc3bd8b7-4ce7-4c46-90a7-373d0a8a3e00 2017-10-03 16:53:00

In [15]:
purchase.head(10)

                                user_id       purchase_time
0  4b44ace4-2721-47a0-b24b-15fbfa2abf85 2017-05-11 04:25:00
1  02e684ae-a448-408f-a9ff-dcb4a5c99aac 2017-09-05 08:45:00
2  4b4bc391-749e-4b90-ab8f-4f6e3c84d6dc 2017-11-20 20:49:00
3  a5dbb25f-3c36-4103-9030-9f7c6241cd8d 2017-01-22 15:18:00
4  46a3186d-7f5a-4ab9-87af-84d05bfd4867 2017-06-11 11:32:00
5  5ae833dc-8866-4baa-9617-2009d6474ffa 2017-07-26 16:46:00
6  70688015-a755-4b8a-a963-3528d85c8048 2017-09-24 08:05:00
7  c504ff0d-eefe-472b-826c-471142311857 2017-05-02 07:56:00
8  99ad37b5-30b1-4a06-ad47-d9d2d60cdb07 2017-02-20 11:11:00
9  4b44ace4-2721-47a0-b24b-15fbfa2abf85 2017-05-11 04:18:00

## Compare the number of visits to the number to the number of purchases

In [39]:
# Merge the visits and cart dataframes
visits_cart = pd.merge(visits, cart, how='left')

print(visits_cart.shape[0])

# Total number of users who visited, but did not add an item to the cart
no_cart = visits_cart.cart_time.isnull().sum()

# Total number of visitors
total_visits = visits.user_id.count()

# Calculate the percentage of how many users visited but add an item to the cart
visit_no_purchase = round((no_cart / total_visits)*100, 2)

2000

## Compare the number of times an item was placed in the cart to the number of checkouts began.

In [42]:
# Merge the cart and checkout dataframaes
cart_checkout = pd.merge(cart, checkout, how = 'left')

# Total number of users who added an item to the cart
added_to_cart = cart.user_id.count()

# Total number of users who added an item to the cart, but did not checkout
cart_no_checkout = cart_checkout.checkout_time.isnull().sum()

# Calculate the percentage of how many users added items to the cart, but did not checkout
not_checked_out = round((cart_no_checkout / added_to_cart) *100, 2)

## Compare the number of checkouts began to the number of purchases made.

In [45]:
# Merge all dataframes into one
all_data = visits.merge(cart, how='left').merge(checkout, how='left').merge(purchase, how='left')

# Filter the users who began the checkout process, but did not make a purchase
began_checkout_no_purchase = all_data[
    (all_data.checkout_time.notnull()) & (all_data.purchase_time.isnull())
]

# Count the number of users who began the checkout process
began_checkout = all_data.checkout_time.notnull().sum()

# Count the number to users who began checkout, but didn't make a purchase
count_began_checkout_no_purchase = len(began_checkout_no_purchase)


# Calculate the percentage of users who began checkout, but didn't make a purchase
percentage_began_checkout_no_purchase = round((count_began_checkout_no_purchase / began_checkout) *100, 2)

## Average checkout time

In [52]:
# Calculate average time from initial visit to final purchase
all_data['time_til_purchase'] = all_data.purchase_time - all_data.visit_time

average_checkout_time = all_data.time_til_purchase.mean()
all_data.head(10)

,user_id,visit_time,cart_time,checkout_time,purchase_time,time_til_purchase
0,943647ef-3682-4750-a2e1-918ba6f16188,2017-04-07 15:14:00,NaT,NaT,NaT,NaT
1,0c3a3dd0-fb64-4eac-bf84-ba069ce409f2,2017-01-26 14:24:00,2017-01-26 14:44:00,2017-01-26 14:54:00,2017-01-26 15:08:00,0 days 00:44:00
2,6e0b2d60-4027-4d9a-babd-0e7d40859fb1,2017-08-20 08:23:00,2017-08-20 08:31:00,NaT,NaT,NaT
3,6879527e-c5a6-4d14-b2da-50b85212b0ab,2017-11-04 18:15:00,NaT,NaT,NaT,NaT
4,a84327ff-5daa-4ba1-b789-d5b4caf81e96,2017-02-27 11:25:00,NaT,NaT,NaT,NaT
5,7bc62113-d51d-4e6b-85e0-1cf29e3de74a,2017-06-03 20:05:00,NaT,NaT,NaT,NaT
6,6f22cd44-bc63-4449-a9af-2651859da2f9,2017-03-18 23:09:00,NaT,NaT,NaT,NaT
7,49a6399b-c095-4e42-92eb-af90abe2bb6a,2017-01-10 12:09:00,NaT,NaT,NaT,NaT
8,653c095d-fd74-40dd-ae3b-5a69a2613629,2017-06-27 19:21:00,NaT,NaT,NaT,NaT
9,3d9fdac1-aae3-4a01-b448-934d12047468,2017-09-24 06:43:00,NaT,NaT,NaT,NaT

## Findings

In [56]:
print(f'{total_visits} total visits\n{no_cart} did not make a purchase\n{visit_no_purchase}% of users visited the website, but did not check out.\n')

print(f'{added_to_cart} users added items to the cart\n{cart_no_checkout} users added items to the cart but did not checkout\n{not_checked_out}% users added items to the cart but did not checkout\n')

print(f'{began_checkout} users began the checkout process.')

print(f'{count_began_checkout_no_purchase} users began the checkout process, but did not make a purchase.')

print(f'{percentage_began_checkout_no_purchase}% of users began the checkout process, but did not make a purchase.\n')

print(f'The weakest part of the funnel is the drop-off from visiting the website to adding items to the cart or checking out, with an {visit_no_purchase}% drop-off.')

print(f'The average time from initial visit to final purchase is {average_checkout_time}')

2000 total visits
1652 did not make a purchase
82.6% of users visited the website, but did not check out.

348 users added items to the cart
122 users added items to the cart but did not checkout
35.06% users added items to the cart but did not checkout

334 users began the checkout process.
82 users began the checkout process, but did not make a purchase.
24.55% of users began the checkout process, but did not make a purchase.

The weakest part of the funnel is the drop-off from visiting the website to adding items to the cart or checking out, with an 82.6% drop-off.
The average time from initial visit to final purchase is 0 days 00:43:12.380952380